### ISSUE TITLE
Write a release post for v5.0

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#55]
- [x] Full changelog. 
- [x] General what's new section that just talks about various new features, new reddit functionality, etc. 
- [x] Section explaining why we jumped from v3 to v5. 
- [x] Call for developers in the future.

**Comment by creesch** [comment]
Updated the issue with a checklist with stuff and moved it to in progress on the project board.

**Comment by creesch** [comment]
Things I specifically want to point out:

- The context menu (what it is, what moved there and why)
- Toolbox user profiles

**Comment by creesch** [comment]
# Title: Toolbox 5 is here! Supports both old and new reddit 

Hi everyone! 

We have some exciting news today in the form of toolbox version 5! 

## Before we start, we can use help with the project. 

Toolbox is an open source project, over the years we have had a variety of people contributing. At the moment the main people contributing are /u/geo1088 and me. Both of us work on it as much as we can but there are times where simply little work is done as we both also are busy outside of the internet (shocking, I know). 
So toolbox can use more people contributing. This can be in the form of code but also documentation. If you have the time and want to contribute we would very much appreciate that! You can have a look at the [contributing document](https://github.com/toolbox-team/reddit-moderator-toolbox-redesign/blob/master/CONTRIBUTING.md) **update repo name** to get started.

With that out of the way we can continue with the rest of the release post!

## Wait?! What happened to toolbox v4?

Toolbox v4 is the version we developed most of the reddit redesign features on, work on this version started almost two years ago. Meanwhile toolbox v3 was maintained for old reddit. Somewhere around last December we decided to start combining both versions into one that supports both old and new reddit. This is the version we are releasing today as version5! 

## So what's new?
A lot of stuff actually! A full changelog can be found here **include changelog url**. We will highlight some of the bigger features in below.

### A ton of code improvements 
While not very visible we did a **a lot** of refactoring of old code to improve the code base and stability of toolbox. We also made sure to include more technical documentation on the github repository so it should be easier for people to contribute to the project. 

### UI/UX updates. 
We also put a lot of effort in updating the UI/UX, the main look and feel should be mostly the same but we took care to give some elements a bit more breathing room and we also updated the icons to be a bit more consistent and less busy. 

### Context menu 
A specific part of what has changed as far as the UI goes is the context menu. This is a new menu found on the left side of your screen just above the modbar. 
It will be visible when in the context of the page a toolbox action is visible. For example: 

- Comment flat view. 
- Toolbox subreddit configuration. 
- Managing usernotes.
- Opening the new toolbox profile functionality from a user profile page. 

[Here is how it looks in idle state](https://www.creesch.com/dump/img/img_5cfc0836d7602.png) and [here is how it looks when you hover over it](https://www.creesch.com/dump/img/img_5cfc086510424.png)(contents varies of course).

### Toolbox user profiles 
A lot of people aren't the biggest fans of how profiles work on reddit these days and the classic overview sort of works but we figured thinks could be better. So we decided to recreate user profiles in a toolbox overlay! 
[Here is how my profile looks in it](https://www.creesch.com/dump/img/img_5cfc0912b92bd.png), as you can see it is heavily inspired by the classic reddit profiles but has some extra features: 

- Hide unmoddable content. 
- Hide mod actions. 
- Enhanced profile searching. 
- Options to automatically open this overlay when visiting profiles. 
- Profile button next to usernames on subreddits you mod. 

### Action history 
Toolbox already offered an option to show automod action reasons under removed content. You will now also see a button called "show recent actions" that on expansion will show a table with all mod actions recently taken on an item by any mod. 
Note: this is done by looking at the last 500 items in the modlog so will only work on recently modded content. 


### Improved RES nightmode support
RES nightmode support is now done through some clever CSS filters. This means that we no longer have to maintain a separate theme for nightmode and any future new functionality automatically will work in nightmode. Similarly if RES nightmode changes things this should not effect toolbox too much. 

##Release status per browser

- Chrome: published on store.
    - Opera users should switch to the chrome store version of toolbox. The one in the Opera store will no longer be updated. 
    - Edge chromium: use the chrome store version. 
- Edge: The "old" version of Edge will no longer be supported. We will be focusing on the new chromium based Edge. 
- Firefox: published on AMO.

**Comment by creesch** [comment]
# Changelog

- Replace impostor kitteh with queue creature if enabled on redesign reddit.
- RUN SNOO RUN!
- Redesign: All toolbox user buttons now show on the hover card by default. hey can still be shown next to the username with a setting switch. We have gone for the hovercard by default as that means we have to add less to reddit and this should be beneficial for reddit performance.
- Redesign: toolbox removal reasons.
- Redesign: History button, mod button. 
- Redesign: Mod macros.
- Profile pro module: Show profiles in a toolbox overlay with various search and filter functions. Can be automatically opened when viewing profiles, from the context menu and a button next to usernames in subreddits you moderate. 
- Comment context popup has been rewritten and given a seperate button.
- Comment flatview has been reworked and is now accessible through the new context menu. 
- Action table: an evolution of the automod action reason functionality that shows all recent actions taken on an item. 
- API requests have been refactored to go through the background page making things work better in chrome. 
- Moderated subreddits now gives access to more subreddit related things.
- UX/UI: Toolbox now has a context menu that gives access to functionality depending on the page context. 
- UI: Icons have been updated. 
- UI: Styling has been updated to give a bit more space where needed. 
- UI: Better RES nightmode support.
- UI: Better modmail nightmode support for firefox.
- Ooooh that is a pretty balloon. 
- UI: The tooltip on a collapsed modbar has been reworked. 
- Comment nuke has been rewritten to make use of the API and therefore be less error prone.
- Code refactoring: Stricter ESLint rules.
- Technical documentation: JSDocs 
- Technical documentation: Github wiki pages for third party implementation of toolbox usernotes and other features using wiki storage.
- Technical documentation: Cleaned up CONTRIBUTING.md.
- Technical documentation: Programming style guide.
- Code refactoring.
- CSS refactoring.
- Code refactoring.
- Did we already mention we refactored a lot of code?

**Comment by SpyTec** [comment]
Reddit post feedback:

* Contributing section could use with Discord link as well, it being in contributing.md isn't good enough. One thing to add might be to list a few things that could be implemented/fixed - concrete examples that's good for first-time contributors to the project.
* I'm assuming this is the firefighting section: "Wait?! What happened to toolbox v4?". Doesn't address disabling old toolbox well enough, it just says that we are just combining the two. If anything it should explain why it's being merged, why just v4 is disabled and not either or/both.
* "So what's new?" 
  * should not put useless info for the consumers in the beginning. 
  * "A ton of code improvements" should be at the bottom of the list. 
  * UI/UX section can use a picture comparison (geo can do that, he's young)
  * General reordering to 1. component changes, 2. new components, 3. code/project specific
* Nitpick: reddit should be Reddit - marketing puts it as bit R 

Spacing issues:

* `as version5!`
* `over it(contents varies of course).`

Wasn't notifications refactor supposed to be part of this update too? I.e. custom notifications that's not part of Reddit? We still get "Trending" notifications from Reddit which can't be disabled for some people AFAIK.

**Comment by creesch** [comment]
> Contributing section could use with Discord link as well, 

I'll take this into consideration. Frankly I think I might rather have people going over the document first to get an idea about what is needed instead of flooding into discord asking "how can I help?" without having read the document. Does that make sense?

> One thing to add might be to list a few things that could be implemented/fixed - concrete examples that's good for first-time contributors to the project.

I think we need to work on labeling our issues here properly as there already is a "help needed" label and we possibly could also triage our issues and add "good first issue" label or something. 

> Doesn't address disabling old toolbox well enough, 

To clarify, we are not disabling old toolbox. We are disabling the redesign test version, the majority of users are still on the version that is going to keep working. 
I did add a bunch more information to clarify a few things. 

> "So what's new?" 

Changed the order around.

> UI/UX section can use a picture comparison

Yeah we can do that, though most of the UI stuff will be visible once they update anyway. The things I included screenshots for are those things people might not see right away. 

> reddit should be Reddit - marketing puts it as bit R

It used to be reddit... But you are right. 

> Wasn't notifications refactor supposed to be part of this update too? 

Yes! Added that in.

**Comment by creesch** [comment]
I realized this is a rather big release so wanted to be prepared for the mozilla review. 

# firefox reviewer notes

This is a rather extensive update of this extension with a lot of focus on cleaning up code an removing unused code. In relation with feedback we got on previous version of toolbox there are two important changes in regards to security.

The first is the removal of an eval instance in our code. 

The second one is further implementation of DOMPurify. In a previous version we already added DOMPurify in a few areas. In this version we have gone a step further through the creation of two utility functions that make it possibly to put all outside input through DOMpurify. These functions are `TBStorage.purify` for simple strings and `TBStorage.purifyObject` which will iterate over a complete object and sanitize all data within it. 


I am not sure if this is relevant for the review but think it is important anyway.
In addition to security we also have made it more clear where toolbox stands on privacy. We already had a privacy policy but as AMO lacks a place to link to it our firefox users would not have had easy access to it. To make this more clear we  linked to the privacy policyin the toolbox about tab in the toolbox settings overlay. We also included a copy of our privacy policy in the repository of toolbox for people.

**Comment by Geo1088** [comment]
v5 released \o/
